# Question 3 Analysis

**Is the gap between developed and developing countries closing**

In [1]:
# import all relevant libraries --> can't use utils since it is a jupyter notebook
import streamlit as st
import pandas as pd
from pathlib import Path
import plotly.express as px
import numpy as np

In [4]:
CWD = Path.cwd()
print(CWD)

ROOT = CWD.parent

IN_RAW = ROOT/"app"/"data"/"output"

OUT_CLEAN = ROOT/"app"/"data"/"output"

OUT_TABLES = ROOT/"app"/"data"/"tables"

IN_DATASET = ROOT/"app"/"data"/"output"/"question1" #<---- here is what we need

print(ROOT)
print(IN_RAW)
print(IN_DATASET)

# IN_RAW.mkdir(parents=True, exist_ok=True)
# OUT_CLEAN.mkdir(parents=True, exist_ok=True)
# OUT_TABLES.mkdir(parents=True, exist_ok=True)

c:\Users\dirai\Documents\GitHub\kldr-project\scripts
c:\Users\dirai\Documents\GitHub\kldr-project
c:\Users\dirai\Documents\GitHub\kldr-project\app\data\output
c:\Users\dirai\Documents\GitHub\kldr-project\app\data\output\question1

In [6]:
df_raw = pd.read_csv(IN_DATASET/"final_panel_for_regression.csv")

In [7]:
df_q3 = df_raw.copy()

In [8]:
df_q3

,country_code,country_name_x,year,Adoption_Business_Computers,Adoption_Business_Internet,Adoption_People_Internet_Usage,Adoption_People_Computer_Usage,Digital_CustumerServices,Digital_Delivery,Digital_Presence,...,Ecom_Orders_Receiving,Exports_Digital_Service,Imports_Digital_Service,Infrastructure_Extranet,Infrastructure_Intranet,Infrastructure_LAN,is_developing,gdp_per_capita,population,internet_usage_pct
0,ABW,Aruba,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.300000e+13,2.700000e+14,NaN,NaN,NaN,0,27324.555426,101838.0,62.0000
1,ABW,Aruba,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.600000e+13,2.910000e+14,NaN,NaN,NaN,0,28037.869793,102591.0,69.0000
2,ABW,Aruba,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.040000e+14,3.360000e+14,NaN,NaN,NaN,0,27341.227428,104110.0,74.0000
3,ABW,Aruba,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.300000e+13,3.530000e+14,NaN,NaN,NaN,0,28668.720420,105675.0,78.9000
4,ABW,Aruba,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.500000e+13,4.110000e+14,NaN,NaN,NaN,0,27914.843344,106807.0,83.7800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2362,ZWE,Zimbabwe,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.600000e+13,5.220000e+14,NaN,NaN,NaN,1,1377.639277,14600294.0,23.1200
2363,ZWE,Zimbabwe,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.600000e+13,3.390000e+14,NaN,NaN,NaN,1,1422.193460,14812482.0,24.4000
2364,ZWE,Zimbabwe,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.400000e+13,2.480000e+14,NaN,NaN,NaN,1,1471.394890,15034452.0,25.0000
2365,ZWE,Zimbabwe,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.900000e+13,2.630000e+14,NaN,NaN,NaN,1,1356.838211,15271368.0,26.5883
2366,ZWE,Zimbabwe,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.400000e+13,2.580000e+14,NaN,NaN,NaN,1,1230.191557,15526888.0,29.2986

In [14]:
df_q3_grouped = df_q3.groupby(["year", "is_developing"])

In [16]:
# For example, let's look at the data for developing countries (1) in the year 2015
group_2015_developing = df_q3_grouped.get_group((2015, 1))
group_2015_developing

,country_code,country_name_x,year,Adoption_Business_Computers,Adoption_Business_Internet,Adoption_People_Internet_Usage,Adoption_People_Computer_Usage,Digital_CustumerServices,Digital_Delivery,Digital_Presence,...,Ecom_Orders_Receiving,Exports_Digital_Service,Imports_Digital_Service,Infrastructure_Extranet,Infrastructure_Intranet,Infrastructure_LAN,is_developing,gdp_per_capita,population,internet_usage_pct
13,AFG,Afghanistan,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.110000e+14,1.080000e+14,NaN,NaN,NaN,1,565.569730,33831764.0,8.2600
24,AGO,Angola,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.100000e+13,7.800000e+15,NaN,NaN,NaN,1,3213.902611,28157798.0,22.0000
38,ALB,Albania,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.410000e+14,1.930000e+14,NaN,NaN,NaN,1,3981.726623,2880703.0,56.9000
58,ARG,Argentina,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.130000e+15,6.913000e+15,NaN,NaN,NaN,1,13679.626498,43477012.0,68.0431
72,ARM,Armenia,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.890000e+14,1.920000e+14,NaN,NaN,NaN,1,3512.393503,3004600.0,59.1008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2310,WSM,Samoa,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.900000e+13,2.600000e+13,NaN,NaN,NaN,1,4084.360838,201782.0,25.4070
2326,YEM,"Yemen, Rep.",2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.400000e+13,3.710000e+14,NaN,NaN,NaN,1,1362.173812,31159379.0,24.0854
2333,ZAF,South Africa,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.220000e+15,5.984000e+15,NaN,NaN,NaN,1,6112.273825,56723537.0,51.9191
2347,ZMB,Zambia,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.400000e+14,2.680000e+14,NaN,NaN,NaN,1,1295.877887,16399089.0,8.8000
2361,ZWE,Zimbabwe,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.300000e+13,5.160000e+14,NaN,NaN,NaN,1,1386.418559,14399013.0,22.7428

In [19]:
avg_adoption_df = df_q3_grouped["internet_usage_pct"].mean().reset_index()

In [20]:
avg_adoption_df

    year  is_developing  internet_usage_pct
0   2010              0           65.005413
1   2010              1           16.791466
2   2011              0           67.857206
3   2011              1           19.415603
4   2012              0           71.091410
5   2012              1           22.113164
6   2013              0           73.712394
7   2013              1           24.440426
8   2014              0           75.939177
9   2014              1           27.605911
10  2015              0           77.906063
11  2015              1           30.828766
12  2016              0           80.626981
13  2016              1           34.673499
14  2017              0           82.474557
15  2017              1           39.059771
16  2018              0           84.287784
17  2018              1           43.470324
18  2019              0           85.776210
19  2019              1           46.543166
20  2020              0           88.095091
21  2020              1           51.601478
22  2021              0           90.460767
23  2021              1           57.821633
24  2022              0           91.123055
25  2022              1           60.617321
26  2023              0           91.805537
27  2023              1           68.904287

In [21]:
OUT_QUESTION3 = ROOT/"app"/"data"/"output"/"question3"

avg_adoption_df.to_csv(OUT_QUESTION3/"avg_adoption_long.csv", index = False)

#### with help of AI: for artistic display we need clean WIDE FORMAT

In [22]:
avg_adoption_df_wide = avg_adoption_df.pivot(index = "year", 
                                            columns = "is_developing",
                                            values="internet_usage_pct"
                                            )

In [23]:
avg_adoption_df_wide

is_developing          0          1
year
2010           65.005413  16.791466
2011           67.857206  19.415603
2012           71.091410  22.113164
2013           73.712394  24.440426
2014           75.939177  27.605911
2015           77.906063  30.828766
2016           80.626981  34.673499
2017           82.474557  39.059771
2018           84.287784  43.470324
2019           85.776210  46.543166
2020           88.095091  51.601478
2021           90.460767  57.821633
2022           91.123055  60.617321
2023           91.805537  68.904287

In [25]:
avg_adoption_df_wide.to_csv(OUT_QUESTION3/"avg_adoption_wide.csv")