# Question 1: Global Digital Trade

- Which countries lead in digital service exports?
- How has digital trade evolved over the past decade?

## Which countries lead in digital service exports?

We already have the top 10 or so to say top 9 table

But I want to do an interactiv viz so users can see the top whatsoever they want to see

#### First let's create a table only with countries and their exports (maybe also imports?)

In [2]:
# import all relevant libraries --> can't use utils since it is a jupyter notebook
import streamlit as st
import pandas as pd
from pathlib import Path
import plotly.express as px
import numpy as np

In [9]:
CWD = Path.cwd()
print(CWD)

ROOT = CWD.parent

IN_RAW = ROOT/"app"/"data"/"output"

OUT_CLEAN = ROOT/"app"/"data"/"output"

OUT_TABLES = ROOT/"app"/"data"/"tables"

OUT_QUESTION1 = ROOT/"app"/"data"/"output"/"question1"

print(ROOT)
print(IN_RAW)

IN_RAW.mkdir(parents=True, exist_ok=True)
OUT_CLEAN.mkdir(parents=True, exist_ok=True)
OUT_TABLES.mkdir(parents=True, exist_ok=True)

c:\Users\dirai\Documents\GitHub\kldr-project\scripts
c:\Users\dirai\Documents\GitHub\kldr-project
c:\Users\dirai\Documents\GitHub\kldr-project\app\data\output

In [6]:
df_raw = pd.read_csv(IN_RAW/"df_UNCTAD_long_tidy.csv")

df = df_raw.copy()

df

      country_code country_name           indicator_name  year  value
0              ABW        Aruba  Exports_Digital_Service  2010   83.0
1              ABW        Aruba  Exports_Digital_Service  2011   96.0
2              ABW        Aruba  Exports_Digital_Service  2012  104.0
3              ABW        Aruba  Exports_Digital_Service  2013   73.0
4              ABW        Aruba  Exports_Digital_Service  2014   75.0
...            ...          ...                      ...   ...    ...
14583          ZWE     Zimbabwe  Imports_Digital_Service  2019  263.0
14584          ZWE     Zimbabwe  Imports_Digital_Service  2020  258.0
14585          ZWE     Zimbabwe  Imports_Digital_Service  2021    NaN
14586          ZWE     Zimbabwe  Imports_Digital_Service  2022    NaN
14587          ZWE     Zimbabwe  Imports_Digital_Service  2023    NaN

[14588 rows x 5 columns]

In [8]:
df_exports_imports = df[df["indicator_name"].isin(["Exports_Digital_Service", "Imports_Digital_Service"])]

df_exports_imports

      country_code country_name           indicator_name  year  value
0              ABW        Aruba  Exports_Digital_Service  2010   83.0
1              ABW        Aruba  Exports_Digital_Service  2011   96.0
2              ABW        Aruba  Exports_Digital_Service  2012  104.0
3              ABW        Aruba  Exports_Digital_Service  2013   73.0
4              ABW        Aruba  Exports_Digital_Service  2014   75.0
...            ...          ...                      ...   ...    ...
14583          ZWE     Zimbabwe  Imports_Digital_Service  2019  263.0
14584          ZWE     Zimbabwe  Imports_Digital_Service  2020  258.0
14585          ZWE     Zimbabwe  Imports_Digital_Service  2021    NaN
14586          ZWE     Zimbabwe  Imports_Digital_Service  2022    NaN
14587          ZWE     Zimbabwe  Imports_Digital_Service  2023    NaN

[5642 rows x 5 columns]

In [ ]:
out_exports_imports_table = OUT_QUESTION1/ "df_exports_imports.csv"

#df_exports_imports.to_csv(out_exports_imports_table, index=False)

#print(f"Sucessfully saved Exports and Imports Table to: {out_exports_imports_table}")

Sucessfully saved Exports and Imports Table to: c:\Users\dirai\Documents\GitHub\kldr-project\app\data\output\question1\df_exports_imports.csv

## After importing to page, we have to adjust some things like number format

In [14]:
df_exports_imports["value_true"] = df["value"] * 1_000_000 # multiply by millions

df_exports_imports.sort_values(["indicator_name", "year", "value_true"], ascending=[True, True, False], inplace=True)

df_exports_imports["rank"] = df_exports_imports.groupby(["indicator_name", "year"])["value_true"].rank(method="dense", ascending=False).astype("Int64") # before int didnt work because we still have some N/A values

# create nicely formatted dollar string

df_exports_imports["value_formatted"] = df_exports_imports["value_true"].apply(lambda x: f"${x:,.0f}")

C:\Users\dirai\AppData\Local\Temp\ipykernel_22200\114322496.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_exports_imports["value_true"] = df["value"] * 1_000_000 # multiply by millions
C:\Users\dirai\AppData\Local\Temp\ipykernel_22200\114322496.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_exports_imports.sort_values(["indicator_name", "year", "value_true"], ascending=[True, True, False], inplace=True)
C:\Users\dirai\AppData\Local\Temp\ipykernel_22200\114322496.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_exports_imports["rank"] = df_exports_imports.groupby(["indicator_name", "year"])["value_true"].rank(method="dense", ascending=False).astype("Int64") # before int didnt work because we still have some N/A values
C:\Users\dirai\AppData\Local\Temp\ipykernel_22200\114322496.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_exports_imports["value_formatted"] = df_exports_imports["value_true"].apply(lambda x: f"${x:,.0f}")

In [20]:
df_exports_imports.head(50)

,country_code,country_name,indicator_name,year,value,value_true,rank,value_formatted
14294,WLD,World,Exports_Digital_Service,2010,1835732.0,1.835732e+12,1,"$1,835,732,000,000"
14126,USA,United States,Exports_Digital_Service,2010,329324.0,3.293240e+11,2,"$329,324,000,000"
5026,GBR,United Kingdom,Exports_Digital_Service,2010,221705.0,2.217050e+11,3,"$221,705,000,000"
3528,DEU,Germany,Exports_Digital_Service,2010,118296.0,1.182960e+11,4,"$118,296,000,000"
4914,FRA,France,Exports_Digital_Service,2010,95231.0,9.523100e+10,5,"$95,231,000,000"
9926,NLD,Netherlands,Exports_Digital_Service,2010,91658.0,9.165800e+10,6,"$91,658,000,000"
6160,IND,India,Exports_Digital_Service,2010,83417.0,8.341700e+10,7,"$83,417,000,000"
6300,IRL,Ireland,Exports_Digital_Service,2010,70816.0,7.081600e+10,8,"$70,816,000,000"
2352,CHE,Switzerland,Exports_Digital_Service,2010,66749.0,6.674900e+10,9,"$66,749,000,000"
6902,JPN,Japan,Exports_Digital_Service,2010,62241.0,6.224100e+10,10,"$62,241,000,000"
2604,CHN,China,Exports_Digital_Service,2010,56020.0,5.602000e+10,11,"$56,020,000,000"
8078,LUX,Luxembourg,Exports_Digital_Service,2010,54661.0,5.466100e+10,12,"$54,661,000,000"
1092,BEL,Belgium,Exports_Digital_Service,2010,47373.0,4.737300e+10,13,"$47,373,000,000"
2254,CAN,Canada,Exports_Digital_Service,2010,44406.0,4.440600e+10,14,"$44,406,000,000"
6720,ITA,Italy,Exports_Digital_Service,2010,41036.0,4.103600e+10,15,"$41,036,000,000"
12250,SGP,Singapore,Exports_Digital_Service,2010,37658.0,3.765800e+10,16,"$37,658,000,000"
13062,SWE,Sweden,Exports_Digital_Service,2010,31426.0,3.142600e+10,17,"$31,426,000,000"
5474,HKG,"Hong Kong SAR, China",Exports_Digital_Service,2010,27784.0,2.778400e+10,18,"$27,784,000,000"
11858,RUS,Russian Federation,Exports_Digital_Service,2010,17631.0,1.763100e+10,19,"$17,631,000,000"
700,AUT,Austria,Exports_Digital_Service,2010,17447.0,1.744700e+10,20,"$17,447,000,000"
7560,KOR,"Korea, Rep.",Exports_Digital_Service,2010,17369.0,1.736900e+10,21,"$17,369,000,000"
6594,ISR,Israel,Exports_Digital_Service,2010,14804.0,1.480400e+10,22,"$14,804,000,000"
9996,NOR,Norway,Exports_Digital_Service,2010,13484.0,1.348400e+10,23,"$13,484,000,000"
4816,FIN,Finland,Exports_Digital_Service,2010,13041.0,1.304100e+10,24,"$13,041,000,000"
3752,DNK,Denmark,Exports_Digital_Service,2010,12913.0,1.291300e+10,25,"$12,913,000,000"
2016,BRA,Brazil,Exports_Digital_Service,2010,12702.0,1.270200e+10,26,"$12,702,000,000"
10738,POL,Poland,Exports_Digital_Service,2010,12108.0,1.210800e+10,27,"$12,108,000,000"
574,AUS,Australia,Exports_Digital_Service,2010,11602.0,1.160200e+10,28,"$11,602,000,000"
12544,SSF,Sub-Saharan Africa,Exports_Digital_Service,2010,9712.0,9.712000e+09,29,"$9,712,000,000"
13412,THA,Thailand,Exports_Digital_Service,2010,9637.0,9.637000e+09,30,"$9,637,000,000"
10514,PHL,Philippines,Exports_Digital_Service,2010,8923.0,8.923000e+09,31,"$8,923,000,000"
5824,HUN,Hungary,Exports_Digital_Service,2010,8030.0,8.030000e+09,32,"$8,030,000,000"
8918,MLT,Malta,Exports_Digital_Service,2010,7484.0,7.484000e+09,33,"$7,484,000,000"
9590,MYS,Malaysia,Exports_Digital_Service,2010,7117.0,7.117000e+09,34,"$7,117,000,000"
3360,CZE,Czechia,Exports_Digital_Service,2010,6884.0,6.884000e+09,35,"$6,884,000,000"
13986,TWN,"Taiwan, China",Exports_Digital_Service,2010,6599.0,6.599000e+09,36,"$6,599,000,000"
6020,IDN,Indonesia,Exports_Digital_Service,2010,6410.0,6.410000e+09,37,"$6,410,000,000"
7658,LBN,Lebanon,Exports_Digital_Service,2010,5663.0,5.663000e+09,38,"$5,663,000,000"
8582,MEX,Mexico,Exports_Digital_Service,2010,5534.0,5.534000e+09,39,"$5,534,000,000"
10906,PRT,Portugal,Exports_Digital_Service,2010,5135.0,5.135000e+09,40,"$5,135,000,000"
434,ARG,Argentina,Exports_Digital_Service,2010,4755.0,4.755000e+09,41,"$4,755,000,000"
11662,ROU,Romania,Exports_Digital_Service,2010,4173.0,4.173000e+09,42,"$4,173,000,000"
7602,KWT,Kuwait,Exports_Digital_Service,2010,3915.0,3.915000e+09,43,"$3,915,000,000"
14504,ZAF,South Africa,Exports_Digital_Service,2010,3890.0,3.890000e+09,44,"$3,890,000,000"
3192,CYP,Cyprus,Exports_Digital_Service,2010,3688.0,3.688000e+09,45,"$3,688,000,000"
14070,UKR,Ukraine,Exports_Digital_Service,2010,3587.0,3.587000e+09,46,"$3,587,000,000"
5320,GRC,Greece,Exports_Digital_Service,2010,2932.0,2.932000e+09,47,"$2,932,000,000"
10080,NZL,New Zealand,Exports_Digital_Service,2010,2717.0,2.717000e+09,48,"$2,717,000,000"
8344,MAR,Morocco,Exports_Digital_Service,2010,2576.0,2.576000e+09,49,"$2,576,000,000"
4284,EGY,"Egypt, Arab Rep.",Exports_Digital_Service,2010,2120.0,2.120000e+09,50,"$2,120,000,000"

In [ ]:
codes_to_exclude = ["WLD", "SFF"]
df_exports_imports = df_exports_imports[~df_exports_imports["country_code"].isin(codes_to_exclude)].copy()

,country_code,country_name,indicator_name,year,value,value_true,rank,value_formatted
14126,USA,United States,Exports_Digital_Service,2010,329324.0,3.293240e+11,2,"$329,324,000,000"
5026,GBR,United Kingdom,Exports_Digital_Service,2010,221705.0,2.217050e+11,3,"$221,705,000,000"
3528,DEU,Germany,Exports_Digital_Service,2010,118296.0,1.182960e+11,4,"$118,296,000,000"
4914,FRA,France,Exports_Digital_Service,2010,95231.0,9.523100e+10,5,"$95,231,000,000"
9926,NLD,Netherlands,Exports_Digital_Service,2010,91658.0,9.165800e+10,6,"$91,658,000,000"
...,...,...,...,...,...,...,...,...
14125,URY,Uruguay,Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan
14237,VEN,"Venezuela, RB",Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan
14293,VUT,Vanuatu,Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan
14405,YEM,"Yemen, Rep.",Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan
14587,ZWE,Zimbabwe,Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan

In [24]:
df_countries_only = df_exports_imports

df_countries_only

df_countries_only["rank"] = df_countries_only.groupby(["indicator_name", "year"])["value_true"].rank(method="dense", ascending=False).astype("Int64")

df_countries_only

,country_code,country_name,indicator_name,year,value,value_true,rank,value_formatted
14126,USA,United States,Exports_Digital_Service,2010,329324.0,3.293240e+11,1,"$329,324,000,000"
5026,GBR,United Kingdom,Exports_Digital_Service,2010,221705.0,2.217050e+11,2,"$221,705,000,000"
3528,DEU,Germany,Exports_Digital_Service,2010,118296.0,1.182960e+11,3,"$118,296,000,000"
4914,FRA,France,Exports_Digital_Service,2010,95231.0,9.523100e+10,4,"$95,231,000,000"
9926,NLD,Netherlands,Exports_Digital_Service,2010,91658.0,9.165800e+10,5,"$91,658,000,000"
...,...,...,...,...,...,...,...,...
14125,URY,Uruguay,Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan
14237,VEN,"Venezuela, RB",Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan
14293,VUT,Vanuatu,Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan
14405,YEM,"Yemen, Rep.",Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan
14587,ZWE,Zimbabwe,Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan

In [28]:
def format_large_number(num):
    if not pd.isna(num):
        num = float(num)
        if num >= 1_000_000_000_000:
            return f"${num / 1_000_000_000_000:,.2f} Trillion"
        elif num >= 1_000_000_000:
            return f"${num / 1_000_000_000:,.2f} Billion"
        elif num >= 1_000_000:
            return f"${num / 1_000_000:,.2f} Million"
        else:
            return f"${num / 1_000:,.2f}"
    return num

df_countries_only["value_formatted_display"] = df_countries_only["value_true"].apply(format_large_number)

df_countries_only

,country_code,country_name,indicator_name,year,value,value_true,rank,value_formatted,value_formatted_display
14126,USA,United States,Exports_Digital_Service,2010,329324.0,3.293240e+11,1,"$329,324,000,000",$329.32 Billion
5026,GBR,United Kingdom,Exports_Digital_Service,2010,221705.0,2.217050e+11,2,"$221,705,000,000",$221.71 Billion
3528,DEU,Germany,Exports_Digital_Service,2010,118296.0,1.182960e+11,3,"$118,296,000,000",$118.30 Billion
4914,FRA,France,Exports_Digital_Service,2010,95231.0,9.523100e+10,4,"$95,231,000,000",$95.23 Billion
9926,NLD,Netherlands,Exports_Digital_Service,2010,91658.0,9.165800e+10,5,"$91,658,000,000",$91.66 Billion
...,...,...,...,...,...,...,...,...,...
14125,URY,Uruguay,Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan,NaN
14237,VEN,"Venezuela, RB",Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan,NaN
14293,VUT,Vanuatu,Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan,NaN
14405,YEM,"Yemen, Rep.",Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan,NaN
14587,ZWE,Zimbabwe,Imports_Digital_Service,2023,NaN,NaN,<NA>,$nan,NaN

In [29]:
df_countries_only.to_csv(OUT_QUESTION1/ "final_country_data.csv", index=False)

# **Question 2: The Relationship Between Digital Adoption and Digital Exports**

This question investigates the causal impact of a country's digital adoption on its volume of digital service exports.

**Our Core Challenge:**
1.  **Endogeneity (Reverse Causality):** Does adoption drive exports, or do exports drive adoption?
2.  **Omitted Variable Bias (OVB):** Are unobserved factors (like stable governance) driving both?

**Our Strategy:**
1.  **Step 1: Data Assembly.** We will build a complete panel dataset by fetching control variables (GDP, Population) and a proxy for digital adoption (Internet Usage %) from the World Bank API and merging it with our existing digital exports data.
2.  **Step 2: Baseline Model (OLS).** We will run a simple OLS regression to establish a baseline correlation, and we will discuss why this model is likely biased.
3.  **Step 3: Robust Model (Fixed Effects).** We will use a Panel Data model with Country Fixed Effects to control for all time-invariant, country-specific omitted variables.
4.  **Step 4: Advanced Model (Instrumental Variable).** We will attempt to find a valid instrument to address endogeneity and estimate the causal effect using a Two-Stage Least Squares (2SLS) model.

## **Step 1.1: Data Acquisition from World Bank API**

Acquire External Control Variables (GDP & Population)**

Our dataset is missing GDP and Population. We will download these two variables from the World Bank API. This is the only external data we need.

We will download this data for all countries from 2010-2023 and save it to a clean intermediate CSV file.

In [46]:
import wbdata
import pandas as pd
from datetime import datetime

# --- Define only the missing indicators ---
indicators = {
    "NY.GDP.PCAP.KD": "gdp_per_capita",
    "SP.POP.TOTL": "population"
}
data_date = (datetime(2010, 1, 1), datetime(2023, 1, 1))

# --- Download data ---
print("Downloading GDP and Population data from World Bank API...")
wb_controls = wbdata.get_dataframe(indicators, country="all", date=data_date)
print("Download complete.")


# --- CORRECTED CLEANING AND PREPARATION ---

# 1. Turn the index (country, date) into regular columns
wb_cleaned = wb_controls.reset_index()

# 2. Rename the columns for consistency
wb_cleaned.rename(columns={'date': 'year', 'country': 'country_name'}, inplace=True)

# 3. Convert year to a number
wb_cleaned['year'] = pd.to_numeric(wb_cleaned['year'])

# 4. Now, create the 'country_code' column from the 'country_name' column
country_mapping = wbdata.get_countries()
country_codes = {item['name']: item['id'] for item in country_mapping}
wb_cleaned['country_code'] = wb_cleaned['country_name'].map(country_codes)

# 5. Drop non-country aggregate rows (like "Africa Eastern and Southern")
wb_cleaned.dropna(subset=['country_code'], inplace=True)

# 6. Save the properly cleaned data to a CSV
wb_cleaned.to_csv("world_bank_cleaned_controls.csv", index=False)

print("\nCleaned control variables (with country_code) saved to 'world_bank_cleaned_controls.csv'")
wb_cleaned.head(50)

Downloading GDP and Population data from World Bank API...
Download complete.

Cleaned control variables (with country_code) saved to 'world_bank_cleaned_controls.csv'

,country_name,year,gdp_per_capita,population,country_code
0,Africa Eastern and Southern,2023,1412.625384,750503764.0,AFE
1,Africa Eastern and Southern,2022,1421.797169,731821393.0,AFE
2,Africa Eastern and Southern,2021,1409.040699,713090928.0,AFE
3,Africa Eastern and Southern,2020,1383.724119,694446100.0,AFE
4,Africa Eastern and Southern,2019,1463.437891,675950189.0,AFE
5,Africa Eastern and Southern,2018,1471.438317,657801085.0,AFE
6,Africa Eastern and Southern,2017,1472.971152,640058741.0,AFE
7,Africa Eastern and Southern,2016,1472.699230,623369401.0,AFE
8,Africa Eastern and Southern,2015,1479.615260,607123269.0,AFE
9,Africa Eastern and Southern,2014,1475.739039,590968990.0,AFE
10,Africa Eastern and Southern,2013,1457.672907,575202699.0,AFE
11,Africa Eastern and Southern,2012,1436.274510,559609961.0,AFE
12,Africa Eastern and Southern,2011,1449.853500,544737983.0,AFE
13,Africa Eastern and Southern,2010,1431.211958,530308387.0,AFE
14,Africa Western and Central,2023,1841.758346,509398589.0,AFW
15,Africa Western and Central,2022,1824.953296,497387180.0,AFW
16,Africa Western and Central,2021,1796.602085,485920997.0,AFW
17,Africa Western and Central,2020,1768.313565,474569351.0,AFW
18,Africa Western and Central,2019,1829.070620,463365429.0,AFW
19,Africa Western and Central,2018,1814.688734,452195915.0,AFW
20,Africa Western and Central,2017,1808.716493,440882906.0,AFW
21,Africa Western and Central,2016,1815.168693,429454743.0,AFW
22,Africa Western and Central,2015,1860.727694,418127845.0,AFW
23,Africa Western and Central,2014,1857.258755,406992047.0,AFW
24,Africa Western and Central,2013,1805.526433,396030207.0,AFW
25,Africa Western and Central,2012,1750.025891,385360349.0,AFW
26,Africa Western and Central,2011,1711.405763,374790143.0,AFW
27,Africa Western and Central,2010,1677.427937,364358270.0,AFW
28,Arab World,2023,6321.017591,482105978.0,ARB
29,Arab World,2022,6369.413205,471352066.0,ARB
30,Arab World,2021,6091.325443,460646603.0,ARB
31,Arab World,2020,5923.373507,453723239.0,ARB
32,Arab World,2019,6351.403270,444281315.0,ARB
33,Arab World,2018,6362.199762,435998060.0,ARB
34,Arab World,2017,6309.558822,428315886.0,ARB
35,Arab World,2016,6335.746273,419808341.0,ARB
36,Arab World,2015,6262.041685,410190679.0,ARB
37,Arab World,2014,6213.194853,400231008.0,ARB
38,Arab World,2013,6200.059175,390954281.0,ARB
39,Arab World,2012,6196.738830,381030177.0,ARB
40,Arab World,2011,6038.370511,372054934.0,ARB
41,Arab World,2010,5953.890883,363568534.0,ARB
42,Caribbean small states,2023,16394.870785,4519904.0,CSS
43,Caribbean small states,2022,15115.628309,4497310.0,CSS
44,Caribbean small states,2021,13195.181516,4479167.0,CSS
45,Caribbean small states,2020,12447.481592,4459302.0,CSS
46,Caribbean small states,2019,13745.432445,4443134.0,CSS
47,Caribbean small states,2018,13729.869643,4407658.0,CSS
48,Caribbean small states,2017,13691.873466,4366140.0,CSS
49,Caribbean small states,2016,13879.439408,4341333.0,CSS

                                  gdp_per_capita   population
country                     date
Africa Eastern and Southern 2023     1412.625384  750503764.0
                            2022     1421.797169  731821393.0
                            2021     1409.040699  713090928.0
                            2020     1383.724119  694446100.0
                            2019     1463.437891  675950189.0
...                                          ...          ...
Zimbabwe                    2014     1380.549271   14207359.0
                            2013     1367.120401   14013808.0
                            2012     1359.458296   13817887.0
                            2011     1184.329610   13595424.0
                            2010     1055.669926   13356548.0

[3724 rows x 2 columns]

In [48]:
wb_cleaned.to_csv(OUT_CLEAN/"world_bank_cleaned_controls.csv", index=False)

## **Step 3: Final Merge and Clean**

The `world_bank_cleaned_controls.csv` file is now ready. We will load it, along with our original local data, and merge them on `country_code` and `year`. We will then drop any rows that have missing values in our key regression variables to produce the final, analysis-ready dataset.

In [51]:
print(IN_RAW)

c:\Users\dirai\Documents\GitHub\kldr-project\app\data\output

In [52]:
df_local = pd.read_csv(IN_RAW / "df_panel.csv")
df_controls = pd.read_csv(IN_RAW/"world_bank_cleaned_controls.csv")

In [53]:
df_panel = df_local.copy()
df_controls = df_controls.copy()

In [57]:
full_panel_data = df_panel.merge(
    df_controls, #No need to subset columns, it's already clean
    on=["country_code", "year"],
    how= "inner" # Use 'inner' to keep only rows that match in both
)

full_panel_data

,country_code,country_name_x,year,Adoption_Business_Computers,Adoption_Business_Internet,Adoption_Peole_Internet,Adoption_People_Compzters,Digital_CustumerServices,Digital_Delivery,Digital_Presence,...,Ecom_Orders_Receiving,Exports_Digital_Service,Imports_Digital_Service,Infrastructure_Extranet,Infrastructure_Intranet,Infrastructure_LAN,is_developing,country_name_y,gdp_per_capita,population
0,ABW,Aruba,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,83.0,270.0,NaN,NaN,NaN,0,Aruba,27324.555426,101838.0
1,ABW,Aruba,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,96.0,291.0,NaN,NaN,NaN,0,Aruba,28037.869793,102591.0
2,ABW,Aruba,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,104.0,336.0,NaN,NaN,NaN,0,Aruba,27341.227428,104110.0
3,ABW,Aruba,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,73.0,353.0,NaN,NaN,NaN,0,Aruba,28668.720420,105675.0
4,ABW,Aruba,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,75.0,411.0,NaN,NaN,NaN,0,Aruba,27914.843344,106807.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2767,ZWE,Zimbabwe,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,89.0,263.0,NaN,NaN,NaN,1,Zimbabwe,1356.838211,15271368.0
2768,ZWE,Zimbabwe,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,74.0,258.0,NaN,NaN,NaN,1,Zimbabwe,1230.191557,15526888.0
2769,ZWE,Zimbabwe,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,Zimbabwe,1311.531000,15797210.0
2770,ZWE,Zimbabwe,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,Zimbabwe,1368.498418,16069056.0
2771,ZWE,Zimbabwe,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,Zimbabwe,1417.557759,16340822.0

In [61]:
full_panel_data.drop("country_name_y", axis=1, inplace=True)

In [66]:
columns_to_transform = ["Exports_Digital_Service", "Imports_Digital_Service"]

full_panel_data[columns_to_transform] = full_panel_data[columns_to_transform] * 1_000_000
full_panel_data.rename(columns={
    "Adoption_Peole_Internet": "Adoption_People_Internet_Usage",
    "Adoption_People_Compzters": "Adoption_People_Computer_Usage"
},
inplace= True)

In [67]:
full_panel_data.head(50)

,country_code,country_name_x,year,Adoption_Business_Computers,Adoption_Business_Internet,Adoption_People_Internet_Usage,Adoption_People_Computer_Usage,Digital_CustumerServices,Digital_Delivery,Digital_Presence,Ecom_Orders_Placing,Ecom_Orders_Receiving,Exports_Digital_Service,Imports_Digital_Service,Infrastructure_Extranet,Infrastructure_Intranet,Infrastructure_LAN,is_developing,gdp_per_capita,population
0,ABW,Aruba,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.300000e+13,2.700000e+14,NaN,NaN,NaN,0,27324.555426,101838.0
1,ABW,Aruba,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.600000e+13,2.910000e+14,NaN,NaN,NaN,0,28037.869793,102591.0
2,ABW,Aruba,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.040000e+14,3.360000e+14,NaN,NaN,NaN,0,27341.227428,104110.0
3,ABW,Aruba,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.300000e+13,3.530000e+14,NaN,NaN,NaN,0,28668.720420,105675.0
4,ABW,Aruba,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000e+13,4.110000e+14,NaN,NaN,NaN,0,27914.843344,106807.0
5,ABW,Aruba,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.200000e+13,3.750000e+14,NaN,NaN,NaN,0,27458.225331,107906.0
6,ABW,Aruba,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.300000e+13,4.040000e+14,NaN,NaN,NaN,0,27719.500731,108727.0
7,ABW,Aruba,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.200000e+13,4.050000e+14,NaN,NaN,NaN,0,29671.135829,108735.0
8,ABW,Aruba,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.400000e+13,4.350000e+14,NaN,NaN,NaN,0,30334.116222,108908.0
9,ABW,Aruba,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.500000e+13,4.270000e+14,NaN,NaN,NaN,0,29576.809715,109203.0
10,ABW,Aruba,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.250000e+14,3.590000e+14,NaN,NaN,NaN,0,21947.995330,108587.0
11,ABW,Aruba,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.190000e+14,4.420000e+14,NaN,NaN,NaN,0,27469.005622,107700.0
12,ABW,Aruba,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.260000e+14,4.890000e+14,NaN,NaN,NaN,0,29917.128029,107310.0
13,ABW,Aruba,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.370000e+14,5.250000e+14,NaN,NaN,NaN,0,31178.473679,107359.0
14,AFG,Afghanistan,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.180000e+14,1.850000e+14,NaN,NaN,NaN,1,542.871030,28284089.0
15,AFG,Afghanistan,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.066000e+15,3.240000e+14,NaN,NaN,NaN,1,525.426983,29347708.0
16,AFG,Afghanistan,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.380000e+14,4.320000e+14,NaN,NaN,NaN,1,568.929021,30560034.0
17,AFG,Afghanistan,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.960000e+14,2.040000e+14,NaN,NaN,NaN,1,580.603833,31622704.0
18,AFG,Afghanistan,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.560000e+14,3.220000e+14,NaN,NaN,NaN,1,575.146246,32792523.0
19,AFG,Afghanistan,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.110000e+14,1.080000e+14,NaN,NaN,NaN,1,565.569730,33831764.0
20,AFG,Afghanistan,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.760000e+14,8.400000e+13,NaN,NaN,NaN,1,563.872337,34700612.0
21,AFG,Afghanistan,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000e+14,7.400000e+13,NaN,NaN,NaN,1,562.769574,35688935.0
22,AFG,Afghanistan,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.490000e+14,1.260000e+14,NaN,NaN,NaN,1,553.125152,36743039.0
23,AFG,Afghanistan,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.140000e+14,8.900000e+13,NaN,NaN,NaN,1,557.861533,37856121.0
24,AFG,Afghanistan,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.750000e+14,7.600000e+13,NaN,NaN,NaN,1,527.834554,39068979.0
25,AFG,Afghanistan,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,408.625855,40000412.0
26,AFG,Afghanistan,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,377.665627,40578842.0
27,AFG,Afghanistan,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,378.066303,41454761.0
28,AGO,Angola,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.300000e+13,7.322000e+15,NaN,NaN,NaN,1,3114.696086,23294825.0
29,AGO,Angola,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000e+13,9.061000e+15,NaN,NaN,NaN,1,3099.942290,24218352.0
30,AGO,Angola,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000e+13,8.922000e+15,NaN,NaN,NaN,1,3236.574945,25177394.0
31,AGO,Angola,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000e+13,9.605000e+15,NaN,NaN,NaN,1,3268.638907,26165620.0
32,AGO,Angola,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000e+13,1.014000e+16,NaN,NaN,NaN,1,3300.735110,27160769.0
33,AGO,Angola,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.100000e+13,7.800000e+15,NaN,NaN,NaN,1,3213.902611,28157798.0
34,AGO,Angola,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.600000e+13,5.433000e+15,NaN,NaN,NaN,1,3020.983328,29183070.0
35,AGO,Angola,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.300000e+13,6.189000e+15,NaN,NaN,NaN,1,2911.600842,30234839.0
36,AGO,Angola,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000e+13,3.796000e+15,NaN,NaN,NaN,1,2775.746423,31297155.0
37,AGO,Angola,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.400000e+13,2.681000e+15,NaN,NaN,NaN,1,2664.438510,32375632.0
38,AGO,Angola,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000e+13,2.010000e+15,NaN,NaN,NaN,1,2433.376373,33451132.0
39,AGO,Angola,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.600000e+13,2.306000e+15,NaN,NaN,NaN,1,2385.448818,34532429.0
40,AGO,Angola,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.600000e+13,2.512000e+15,NaN,NaN,NaN,1,2382.022640,35635029.0
41,AGO,Angola,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.600000e+13,2.345000e+15,NaN,NaN,NaN,1,2334.661043,36749906.0
42,ALB,Albania,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.120000e+14,2.150000e+14,NaN,NaN,NaN,1,3579.824132,2913021.0
43,ALB,Albania,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.140000e+14,2.750000e+14,NaN,NaN,NaN,1,3677.894579,2905195.0
44,ALB,Albania,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.080000e+14,2.350000e+14,NaN,NaN,NaN,1,3720.228765,2900401.0
45,ALB,Albania,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.010000e+14,2.090000e+14,NaN,NaN,NaN,1,3790.680163,2895092.0
46,ALB,Albania,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.860000e+14,1.850000e+14,NaN,NaN,NaN,1,3883.632628,2889104.0
47,ALB,Albania,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.410000e+14,1.930000e+14,NaN,NaN,NaN,1,3981.726623,2880703.0
48,ALB,Albania,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.980000e+14,1.960000e+14,NaN,NaN,NaN,1,4143.989883,2876101.0
49,ALB,Albania,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.680000e+14,NaN,NaN,NaN,1,4283.982627,2873457.0

In [69]:
full_panel_data.to_csv(OUT_CLEAN/"final_master_dataset.csv")
print("Final master dataset with all columns saved to 'final_master_dataset.csv")

Final master dataset with all columns saved to 'final_master_dataset.csv

In [70]:
regression_vars = [
    "Exports_Digital_Service",
    "Adoption_People_Internet_Usage",
    "gdp_per_capita",
    "population"
]

In [71]:
regression_df = full_panel_data.dropna(subset= regression_vars)

In [73]:
len(full_panel_data)

2772

In [72]:
regression_df.to_csv(OUT_CLEAN/"final_panel_for_regression.csv", index = False)

print(f"\nCreated a clean dataset for regression with {len(regression_df)} complete observations.")
print("Saved to 'final_panel_for_regression.csv'")
regression_df.head()

Created a clean dataset for regression with 245 complete observations.
Saved to 'final_panel_for_regression.csv'

,country_code,country_name_x,year,Adoption_Business_Computers,Adoption_Business_Internet,Adoption_People_Internet_Usage,Adoption_People_Computer_Usage,Digital_CustumerServices,Digital_Delivery,Digital_Presence,Ecom_Orders_Placing,Ecom_Orders_Receiving,Exports_Digital_Service,Imports_Digital_Service,Infrastructure_Extranet,Infrastructure_Intranet,Infrastructure_LAN,is_developing,gdp_per_capita,population
75,ARE,United Arab Emirates,2015,97.72,94.72,96.26,98.75,12.69,NaN,73.13,23.74,22.41,2.635500e+16,4.660700e+16,6.41,35.97,55.50,0,43534.997269,8505237.0
140,AUT,Austria,2010,98.17,97.19,99.02,51.13,NaN,NaN,80.19,51.29,17.75,1.744700e+16,1.350400e+16,16.91,28.63,82.67,0,43035.407353,8363404.0
141,AUT,Austria,2011,99.03,98.20,99.39,NaN,NaN,NaN,82.87,59.05,15.04,2.110400e+16,1.573300e+16,NaN,NaN,NaN,0,44146.195681,8391643.0
142,AUT,Austria,2012,98.93,98.22,99.33,50.77,NaN,NaN,82.01,58.65,15.58,2.205500e+16,1.696900e+16,NaN,NaN,NaN,0,44221.459953,8429991.0
145,AUT,Austria,2015,99.38,98.76,99.54,NaN,NaN,NaN,87.46,68.28,17.92,2.238900e+16,1.992800e+16,NaN,NaN,NaN,0,43915.228021,8642699.0

# We almost lose all of our data by dropping NA values... what to do then?

In [ ]:
full_panel_data

,country_code,country_name_x,year,Adoption_Business_Computers,Adoption_Business_Internet,Adoption_People_Internet_Usage,Adoption_People_Computer_Usage,Digital_CustumerServices,Digital_Delivery,Digital_Presence,Ecom_Orders_Placing,Ecom_Orders_Receiving,Exports_Digital_Service,Imports_Digital_Service,Infrastructure_Extranet,Infrastructure_Intranet,Infrastructure_LAN,is_developing,gdp_per_capita,population
0,ABW,Aruba,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.300000e+13,2.700000e+14,NaN,NaN,NaN,0,27324.555426,101838.0
1,ABW,Aruba,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.600000e+13,2.910000e+14,NaN,NaN,NaN,0,28037.869793,102591.0
2,ABW,Aruba,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.040000e+14,3.360000e+14,NaN,NaN,NaN,0,27341.227428,104110.0
3,ABW,Aruba,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.300000e+13,3.530000e+14,NaN,NaN,NaN,0,28668.720420,105675.0
4,ABW,Aruba,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000e+13,4.110000e+14,NaN,NaN,NaN,0,27914.843344,106807.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2767,ZWE,Zimbabwe,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.900000e+13,2.630000e+14,NaN,NaN,NaN,1,1356.838211,15271368.0
2768,ZWE,Zimbabwe,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.400000e+13,2.580000e+14,NaN,NaN,NaN,1,1230.191557,15526888.0
2769,ZWE,Zimbabwe,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1311.531000,15797210.0
2770,ZWE,Zimbabwe,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1368.498418,16069056.0
2771,ZWE,Zimbabwe,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1417.557759,16340822.0

lets try it with interpolation:

In [78]:
# --- Step 2: Define the columns we need to work with ---
# We will focus on the variables for this specific regression.
# I am using your actual column names.

df_analysis = full_panel_data.copy()

In [79]:
df_analysis

,country_code,country_name_x,year,Adoption_Business_Computers,Adoption_Business_Internet,Adoption_People_Internet_Usage,Adoption_People_Computer_Usage,Digital_CustumerServices,Digital_Delivery,Digital_Presence,Ecom_Orders_Placing,Ecom_Orders_Receiving,Exports_Digital_Service,Imports_Digital_Service,Infrastructure_Extranet,Infrastructure_Intranet,Infrastructure_LAN,is_developing,gdp_per_capita,population
0,ABW,Aruba,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.300000e+13,2.700000e+14,NaN,NaN,NaN,0,27324.555426,101838.0
1,ABW,Aruba,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.600000e+13,2.910000e+14,NaN,NaN,NaN,0,28037.869793,102591.0
2,ABW,Aruba,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.040000e+14,3.360000e+14,NaN,NaN,NaN,0,27341.227428,104110.0
3,ABW,Aruba,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.300000e+13,3.530000e+14,NaN,NaN,NaN,0,28668.720420,105675.0
4,ABW,Aruba,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000e+13,4.110000e+14,NaN,NaN,NaN,0,27914.843344,106807.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2767,ZWE,Zimbabwe,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.900000e+13,2.630000e+14,NaN,NaN,NaN,1,1356.838211,15271368.0
2768,ZWE,Zimbabwe,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.400000e+13,2.580000e+14,NaN,NaN,NaN,1,1230.191557,15526888.0
2769,ZWE,Zimbabwe,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1311.531000,15797210.0
2770,ZWE,Zimbabwe,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1368.498418,16069056.0
2771,ZWE,Zimbabwe,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1417.557759,16340822.0

In [81]:
# --- Step 3: The CORRECT way to handle missing data - IMPUTATION ---
# We will sort the data by country and year to ensure the interpolation is done correctly.
df_analysis.sort_values(by=['country_code', 'year'], inplace=True)
df_analysis

,country_code,country_name_x,year,Adoption_Business_Computers,Adoption_Business_Internet,Adoption_People_Internet_Usage,Adoption_People_Computer_Usage,Digital_CustumerServices,Digital_Delivery,Digital_Presence,Ecom_Orders_Placing,Ecom_Orders_Receiving,Exports_Digital_Service,Imports_Digital_Service,Infrastructure_Extranet,Infrastructure_Intranet,Infrastructure_LAN,is_developing,gdp_per_capita,population
0,ABW,Aruba,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.300000e+13,2.700000e+14,NaN,NaN,NaN,0,27324.555426,101838.0
1,ABW,Aruba,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.600000e+13,2.910000e+14,NaN,NaN,NaN,0,28037.869793,102591.0
2,ABW,Aruba,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.040000e+14,3.360000e+14,NaN,NaN,NaN,0,27341.227428,104110.0
3,ABW,Aruba,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.300000e+13,3.530000e+14,NaN,NaN,NaN,0,28668.720420,105675.0
4,ABW,Aruba,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000e+13,4.110000e+14,NaN,NaN,NaN,0,27914.843344,106807.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2767,ZWE,Zimbabwe,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.900000e+13,2.630000e+14,NaN,NaN,NaN,1,1356.838211,15271368.0
2768,ZWE,Zimbabwe,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.400000e+13,2.580000e+14,NaN,NaN,NaN,1,1230.191557,15526888.0
2769,ZWE,Zimbabwe,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1311.531000,15797210.0
2770,ZWE,Zimbabwe,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1368.498418,16069056.0
2771,ZWE,Zimbabwe,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1417.557759,16340822.0

In [84]:
cols_to_impute = ['Adoption_People_Internet_Usage', 'gdp_per_capita', 'population']

df_analysis[cols_to_impute] = df_analysis.groupby('country_code')[cols_to_impute].transform(
    lambda x: x.interpolate(method='linear', limit_direction='both')
)

print("\nPerformed linear interpolation on missing values.")

df_analysis

Performed linear interpolation on missing values.

,country_code,country_name_x,year,Adoption_Business_Computers,Adoption_Business_Internet,Adoption_People_Internet_Usage,Adoption_People_Computer_Usage,Digital_CustumerServices,Digital_Delivery,Digital_Presence,Ecom_Orders_Placing,Ecom_Orders_Receiving,Exports_Digital_Service,Imports_Digital_Service,Infrastructure_Extranet,Infrastructure_Intranet,Infrastructure_LAN,is_developing,gdp_per_capita,population
0,ABW,Aruba,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.300000e+13,2.700000e+14,NaN,NaN,NaN,0,27324.555426,101838.0
1,ABW,Aruba,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.600000e+13,2.910000e+14,NaN,NaN,NaN,0,28037.869793,102591.0
2,ABW,Aruba,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.040000e+14,3.360000e+14,NaN,NaN,NaN,0,27341.227428,104110.0
3,ABW,Aruba,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.300000e+13,3.530000e+14,NaN,NaN,NaN,0,28668.720420,105675.0
4,ABW,Aruba,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000e+13,4.110000e+14,NaN,NaN,NaN,0,27914.843344,106807.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2767,ZWE,Zimbabwe,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.900000e+13,2.630000e+14,NaN,NaN,NaN,1,1356.838211,15271368.0
2768,ZWE,Zimbabwe,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.400000e+13,2.580000e+14,NaN,NaN,NaN,1,1230.191557,15526888.0
2769,ZWE,Zimbabwe,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1311.531000,15797210.0
2770,ZWE,Zimbabwe,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1368.498418,16069056.0
2771,ZWE,Zimbabwe,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1417.557759,16340822.0

In [86]:
# --- Step 4: Final Cleanup ---
# After interpolation, there might still be some rows with NaNs if a country had NO data at all.
# NOW it is safe to drop the few remaining NaNs.
final_vars = ['Exports_Digital_Service', 'Adoption_People_Internet_Usage', 'gdp_per_capita', 'population']
regression_df2 = df_analysis.dropna(subset=final_vars)

print(f"After imputation and final cleanup, we have {len(regression_df)} observations for our regression.")

After imputation and final cleanup, we have 245 observations for our regression.

still no imporvement, lets inverstigate:

In [88]:
df_investigate = full_panel_data[[
    'country_code',
    'year',
    'Exports_Digital_Service',
    'Adoption_People_Internet_Usage'
]].copy()

In [90]:
print("--- DATA DIAGNOSTICS ---")

# Check 1: How many total non-missing values are in each column?
print("\n1. Count of non-missing values per column:")
print(df_investigate.info())

# Check 2: Let's look at a country that SHOULD be there, like the USA.
print("\n2. Data for the United States (USA):")
print(df_investigate[df_investigate['country_code'] == 'USA'])

# Check 3: Let's find which countries have ANY data for 'Adoption_Peole_Internet'
countries_with_adoption_data = df_investigate.dropna(subset=['Adoption_People_Internet_Usage'])['country_code'].unique()
print(f"\n3. Found {len(countries_with_adoption_data)} countries with ANY 'Adoption_People_Internet_Usage' data.")
print(countries_with_adoption_data)

# Check 4: Let's find which countries have ANY data for 'Exports_Digital_Service'
countries_with_exports_data = df_investigate.dropna(subset=['Exports_Digital_Service'])['country_code'].unique()
print(f"\n4. Found {len(countries_with_exports_data)} countries with ANY 'Exports_Digital_Service' data.")
print(countries_with_exports_data)

--- DATA DIAGNOSTICS ---

1. Count of non-missing values per column:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2772 entries, 0 to 2771
Data columns (total 4 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_code                    2772 non-null   object
 1   year                            2772 non-null   int64
 2   Exports_Digital_Service         2526 non-null   float64
 3   Adoption_People_Internet_Usage  261 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 86.8+ KB
None

2. Data for the United States (USA):
     country_code  year  Exports_Digital_Service  \
2604          USA  2010             3.293240e+17
2605          USA  2011             3.689440e+17
2606          USA  2012             3.903080e+17
2607          USA  2013             4.061910e+17
2608          USA  2014             4.344900e+17
2609          USA  2015             4.377370e+17
2610          USA  2016             4.550200e+17
2611          USA  2017             4.982830e+17
2612          USA  2018             5.080320e+17
2613          USA  2019             5.371300e+17
2614          USA  2020             5.467480e+17
2615          USA  2021             6.193890e+17
2616          USA  2022             6.592630e+17
2617          USA  2023             6.804570e+17

      Adoption_People_Internet_Usage
2604                             NaN
2605                             NaN
2606                             NaN
2607                             NaN
2608                             NaN
2609                             NaN
2610                             NaN
2611                             NaN
2612                             NaN
2613                             NaN
2614                             NaN
2615                             NaN
2616                             NaN
2617                             NaN

3. Found 55 countries with ANY 'Adoption_People_Internet_Usage' data.
['AND' 'ARE' 'AUT' 'AZE' 'BEL' 'BGR' 'BIH' 'BLR' 'BOL' 'CHL' 'COL' 'CYP'
 'CZE' 'DEU' 'DNK' 'ECU' 'EGY' 'ESP' 'EST' 'FIN' 'GRC' 'HRV' 'HUN' 'IDN'
 'IRL' 'ISL' 'ITA' 'KAZ' 'KEN' 'KOR' 'LTU' 'LUX' 'LVA' 'MDA' 'MKD' 'MLT'
 'MNG' 'NLD' 'PER' 'PHL' 'POL' 'PRT' 'PRY' 'PSE' 'QAT' 'ROU' 'RUS' 'SAU'
 'SRB' 'SVK' 'SVN' 'SWE' 'THA' 'TUN' 'TUR']

4. Found 194 countries with ANY 'Exports_Digital_Service' data.
['ABW' 'AFG' 'AGO' 'ALB' 'ARE' 'ARG' 'ARM' 'ATG' 'AUS' 'AUT' 'AZE' 'BDI'
 'BEL' 'BEN' 'BFA' 'BGD' 'BGR' 'BHR' 'BHS' 'BIH' 'BLR' 'BLZ' 'BMU' 'BOL'
 'BRA' 'BRB' 'BRN' 'BTN' 'BWA' 'CAF' 'CAN' 'CHE' 'CHL' 'CHN' 'CIV' 'CMR'
 'COD' 'COG' 'COL' 'COM' 'CPV' 'CRI' 'CUW' 'CYM' 'CYP' 'CZE' 'DEU' 'DJI'
 'DMA' 'DNK' 'DOM' 'DZA' 'ECU' 'EGY' 'ESP' 'EST' 'ETH' 'FIN' 'FJI' 'FRA'
 'FRO' 'FSM' 'GAB' 'GBR' 'GEO' 'GHA' 'GIN' 'GMB' 'GNB' 'GNQ' 'GRC' 'GRD'
 'GTM' 'GUY' 'HKG' 'HND' 'HRV' 'HTI' 'HUN' 'IDN' 'IND' 'IRL' 'IRN' 'IRQ'
 'ISL' 'ISR' 'ITA' 'JAM' 'JOR' 'JPN' 'KAZ' 'KEN' 'KGZ' 'KHM' 'KIR' 'KNA'
 'KOR' 'KWT' 'LAO' 'LBN' 'LBR' 'LBY' 'LCA' 'LKA' 'LSO' 'LTU' 'LUX' 'LVA'
 'MAC' 'MAR' 'MDA' 'MDG' 'MDV' 'MEX' 'MKD' 'MLI' 'MLT' 'MMR' 'MNE' 'MNG'
 'MOZ' 'MRT' 'MUS' 'MWI' 'MYS' 'NAM' 'NCL' 'NER' 'NGA' 'NIC' 'NLD' 'NOR'
 'NPL' 'NRU' 'NZL' 'OMN' 'PAK' 'PAN' 'PER' 'PHL' 'PLW' 'PNG' 'POL' 'PRT'
 'PRY' 'PSE' 'PYF' 'QAT' 'ROU' 'RUS' 'RWA' 'SAU' 'SDN' 'SEN' 'SGP' 'SLB'
 'SLE' 'SLV' 'SRB' 'SSD' 'STP' 'SUR' 'SVK' 'SVN' 'SWE' 'SWZ' 'SXM' 'SYC'
 'TCD' 'TGO' 'THA' 'TJK' 'TLS' 'TON' 'TTO' 'TUN' 'TUR' 'TUV' 'TZA' 'UGA'
 'UKR' 'URY' 'USA' 'UZB' 'VCT' 'VEN' 'VNM' 'VUT' 'WSM' 'XKX' 'YEM' 'ZAF'
 'ZMB' 'ZWE']

## Adoption_People_Internet_Usage is not reliable, since there are a lot of NaN values
Let's try it with Adoption_Business

In [ ]:
regression_vars = [
    'Exports_Digital_Service',
    'Adoption_Business_Internet', # <-- THE CORRECTED VARIABLE CHOICE
    'gdp_per_capita',
    'population'
]

In [92]:
# --- Step 3: Create the regression DataFrame by dropping NaNs from this NEW subset ---
# This will only remove a row if one of these FOUR specific columns is empty.
regression_df3 = full_panel_data.dropna(subset=regression_vars)

In [93]:
# --- Step 4: Check the new, hopefully much larger, sample size ---
print(f"\nAfter choosing a better proxy, we have {len(regression_df)} complete observations.")

if len(regression_df) < 500:
    print("\nWARNING: The sample size is still very small. The results will not be reliable.")
    print("This indicates that 'Adoption_Business_Internet' also has poor data overlap.")
    print("You may need to try another proxy like 'Adoption_Business_Computers' or reconsider the analysis.")
else:
    print("This sample size is much better. We can proceed with the analysis.")

After choosing a better proxy, we have 245 complete observations.

WARNING: The sample size is still very small. The results will not be reliable.
This indicates that 'Adoption_Business_Internet' also has poor data overlap.
You may need to try another proxy like 'Adoption_Business_Computers' or reconsider the analysis.

### AFter inspecting all those variables are unreliable ...

I  will try to get them from wbdata

In [94]:
indicators = {
    "IT.NET.USER.ZS": "internet_usage_pct", # Digital Adoption Proxy
}

In [95]:
data_date = (datetime(2010, 1, 1), datetime(2023, 1, 1))

print("Downloading all independent variables from World Bank API...")
df_wb = wbdata.get_dataframe(indicators, country="all", date=data_date)
print("Download complete.")

Downloading all independent variables from World Bank API...
Download complete.

In [96]:
df_wb

                                  internet_usage_pct
country                     date
Africa Eastern and Southern 2023             32.4000
                            2022             30.2000
                            2021             28.2000
                            2020             25.0000
                            2019             22.4000
...                                              ...
Zimbabwe                    2014             16.3647
                            2013             15.5000
                            2012             12.0000
                            2011              8.4000
                            2010              6.4000

[3724 rows x 1 columns]

In [97]:
df_wb = df_wb.reset_index()

In [103]:
df_wb.rename(columns={'date': 'year', 'country': 'country_name'}, inplace=True)

df_wb['year'] = pd.to_numeric(df_wb['year'])

country_mapping = wbdata.get_countries()
country_codes = {item['name']: item['id'] for item in country_mapping}
df_wb['country_code'] = df_wb['country_name'].map(country_codes)

In [105]:
df_wb

                     country_name  year  internet_usage_pct country_code
0     Africa Eastern and Southern  2023             32.4000          AFE
1     Africa Eastern and Southern  2022             30.2000          AFE
2     Africa Eastern and Southern  2021             28.2000          AFE
3     Africa Eastern and Southern  2020             25.0000          AFE
4     Africa Eastern and Southern  2019             22.4000          AFE
...                           ...   ...                 ...          ...
3719                     Zimbabwe  2014             16.3647          ZWE
3720                     Zimbabwe  2013             15.5000          ZWE
3721                     Zimbabwe  2012             12.0000          ZWE
3722                     Zimbabwe  2011              8.4000          ZWE
3723                     Zimbabwe  2010              6.4000          ZWE

[3724 rows x 4 columns]

Now we have the data and can merge it with

In [106]:
df_adoption_clean = df_wb[["country_code", "year", "internet_usage_pct"]]

In [107]:
full_panel_data_complete = pd.merge(
    full_panel_data,
    df_adoption_clean,
    on =["country_code", "year"], 
    how= "left" # This adds 'internet_usage_pct' where it can, and NaN where it can't.
)

In [108]:
regression_vars = [
    'Exports_Digital_Service',
    'internet_usage_pct', # The new, reliable adoption proxy from World Bank
    'gdp_per_capita',
    'population'
]

In [109]:
regression_df = full_panel_data_complete.dropna(subset=regression_vars)

In [114]:
# --- Final Check and Save ---
print(f"\nAfter merging the new adoption data, we have {len(regression_df)} complete observations.")
regression_df.to_csv(OUT_CLEAN/"question1"/ "final_panel_for_regression.csv", index=False)
print("Saved the final regression-ready dataset.")
regression_df.head()

After merging the new adoption data, we have 2367 complete observations.
Saved the final regression-ready dataset.

,country_code,country_name_x,year,Adoption_Business_Computers,Adoption_Business_Internet,Adoption_People_Internet_Usage,Adoption_People_Computer_Usage,Digital_CustumerServices,Digital_Delivery,Digital_Presence,...,Ecom_Orders_Receiving,Exports_Digital_Service,Imports_Digital_Service,Infrastructure_Extranet,Infrastructure_Intranet,Infrastructure_LAN,is_developing,gdp_per_capita,population,internet_usage_pct
0,ABW,Aruba,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.300000e+13,2.700000e+14,NaN,NaN,NaN,0,27324.555426,101838.0,62.00
1,ABW,Aruba,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.600000e+13,2.910000e+14,NaN,NaN,NaN,0,28037.869793,102591.0,69.00
2,ABW,Aruba,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.040000e+14,3.360000e+14,NaN,NaN,NaN,0,27341.227428,104110.0,74.00
3,ABW,Aruba,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.300000e+13,3.530000e+14,NaN,NaN,NaN,0,28668.720420,105675.0,78.90
4,ABW,Aruba,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.500000e+13,4.110000e+14,NaN,NaN,NaN,0,27914.843344,106807.0,83.78

## Now I am about to create my regression model

In [113]:
print(OUT_CLEAN)

c:\Users\dirai\Documents\GitHub\kldr-project\app\data\output

In [115]:
import statsmodels.api as sm

In [117]:
df = pd.read_csv(OUT_CLEAN/"question1"/"final_panel_for_regression.csv")

# --- Prepare variables for the regression ---
# 1. Define the dependent variable (Y) and apply a log transformation
#    (Using your original column name for clarity)

Y= np.log(df["Exports_Digital_Service"] +1)

# 2. Define the independent variables (X)
#    (Using the new, clean column name from the World Bank)

X = df[["internet_usage_pct", "gdp_per_capita", "population"]]

# 3. Apply log transformations to the control variables

X['log_gdp_per_capita'] = np.log(X['gdp_per_capita'] + 1)
X['log_population'] = np.log(X['population'] + 1)

# 4. Select the final set of regressors for the model
X = X[['internet_usage_pct', 'log_gdp_per_capita', 'log_population']]

# 5. Add a constant (the intercept, β₀) to the model
X = sm.add_constant(X)

# --- Run the OLS model ---

model_ols = sm.OLS(Y, X)
results_ols = model_ols.fit()

# --- Print the summary table ---
print("--- OLS Regression Results ---")
print(results_ols.summary())

--- OLS Regression Results ---
                               OLS Regression Results
===================================================================================
Dep. Variable:     Exports_Digital_Service   R-squared:                       0.631
Model:                                 OLS   Adj. R-squared:                  0.630
Method:                      Least Squares   F-statistic:                     1345.
Date:                     Sat, 22 Nov 2025   Prob (F-statistic):               0.00
Time:                             17:52:12   Log-Likelihood:                -5396.9
No. Observations:                     2367   AIC:                         1.080e+04
Df Residuals:                         2363   BIC:                         1.082e+04
Df Model:                                3
Covariance Type:                 nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  2.4023      0.625      3.846      0.000       1.178       3.627
internet_usage_pct     0.0109      0.003      3.590      0.000       0.005       0.017
log_gdp_per_capita     1.4666      0.065     22.439      0.000       1.338       1.595
log_population         1.1576      0.024     48.993      0.000       1.111       1.204
==============================================================================
Omnibus:                     3215.036   Durbin-Watson:                   0.517
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           679961.242
Skew:                          -7.712   Prob(JB):                         0.00
Kurtosis:                      84.587   Cond. No.                         809.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\dirai\AppData\Local\Temp\ipykernel_22200\240136608.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['log_gdp_per_capita'] = np.log(X['gdp_per_capita'] + 1)
C:\Users\dirai\AppData\Local\Temp\ipykernel_22200\240136608.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['log_population'] = np.log(X['population'] + 1)

#### Saving OLS results

In [122]:
out_path_ols_summary = OUT_CLEAN/"question1"/"OLS_results_summary.txt"

In [123]:
out_path_ols_summary.parent.mkdir(parents=True, exist_ok=True)

In [125]:
with open(out_path_ols_summary, "w") as f:
    f.write(str(results_ols.summary()))

print(f"\nSUCCESS: OLS regression summary has been saved to: {out_path_ols_summary}")

SUCCESS: OLS regression summary has been saved to: c:\Users\dirai\Documents\GitHub\kldr-project\app\data\output\question1\OLS_results_summary.txt

In [127]:
regression_df = pd.read_csv(OUT_QUESTION1/"final_panel_for_regression.csv")

# --- Create the 3D Interactive Scatter Plot using Plotly Express ---
fig_3d = px.scatter_3d(
    regression_df,
    x=np.log(regression_df['gdp_per_capita'] + 1),
    y=regression_df['internet_usage_pct'],
    z=np.log(regression_df['Exports_Digital_Service'] + 1),
    color=np.log(regression_df['population'] + 1),
    color_continuous_scale=px.colors.sequential.Plasma, # Using the same theme
    hover_name='country_name_x', # Use the correct column name from your DataFrame
    labels={
        "x": "Log(GDP per Capita)",
        "y": "Internet Usage (%)",
        "z": "Log(Digital Service Exports)",
        "color": "Log(Population)"
    },
    title="3D View: Exports, GDP, and Internet Adoption"
)

# --- Improve the layout for a cleaner look ---
fig_3d.update_layout(
    margin=dict(l=0, r=0, b=0, t=40),
    paper_bgcolor="rgba(0,0,0,0)", # Transparent background
    plot_bgcolor="rgba(0,0,0,0)",  # Transparent background
    font_color="white"             # White text for dark themes
)

# --- Save the plot as an HTML file for your Streamlit app ---
# Make sure your IN_QUESTION1 path is defined
output_path_3d = OUT_QUESTION1 / "interactive_3d_plot.html"
fig_3d.write_html(output_path_3d)
fig_3d.show()

In [128]:


# This assumes IN_QUESTION1 is still defined in your notebook's memory
# If not, redefine it first:
# ROOT = Path.cwd().parent 
# IN_QUESTION1 = ROOT / "app" / "data" / "output" / "question1"

# Define the output path using the exact same filename you used
output_path = OUT_QUESTION1 / "OLS_results_summary.txt"

# --- This is the most important command ---
# It will print the TRUE, absolute path of the file you saved.
print("The file was saved to this exact absolute path:")
print(output_path.resolve())

# It will also check if the file actually exists at that path from the notebook's perspective
if output_path.exists():
    print("\nCONFIRMED: The file exists at this path.")
else:
    print("\nERROR: The file does NOT exist at this path. Please re-run the cell that saves the file.")

The file was saved to this exact absolute path:
C:\Users\dirai\Documents\GitHub\kldr-project\app\data\output\question1\OLS_results_summary.txt

CONFIRMED: The file exists at this path.

In [129]:


# --- Create a DataFrame from the OLS results ---
# We need the coefficients and the confidence intervals
results_df = pd.DataFrame({
    "coefficient": results_ols.params,
    "conf_lower": results_ols.conf_int()[0],
    "conf_upper": results_ols.conf_int()[1]
})

# Drop the 'const' (intercept) because it's usually not plotted
results_df = results_df.drop('const')

# Reset the index to make 'variable' a regular column
results_df.reset_index(inplace=True)
results_df.rename(columns={'index': 'variable'}, inplace=True)

# --- Create the Coefficient Plot using Plotly ---
fig_coef = px.scatter(
    results_df,
    x="coefficient",
    y="variable",
    error_x="conf_upper",  # This tells Plotly how to draw the whiskers
    error_x_minus="conf_lower",
    labels={
        "coefficient": "Coefficient Estimate (Effect Size)",
        "variable": "Variable"
    },
    title="<b>Impact of Key Variables on Digital Exports</b>"
)

# --- Add a vertical line at x=0 ---
# This line is crucial. If a variable's confidence interval (whisker) crosses this line,
# it means the result is not statistically significant.
fig_coef.add_vline(x=0, line_width=2, line_dash="dash", line_color="grey")

# --- Style the plot for a professional look ---
fig_coef.update_layout(
    yaxis_title=None, # Clean up y-axis title
    plot_bgcolor='rgba(0,0,0,0)',
    paper_bgcolor='rgba(0,0,0,0)',
    font_color='#ECEFF4' # Use a nice, soft white font
)
fig_coef.update_yaxes(autorange="reversed") # Puts the most important variable at the top

# --- Save the plot as an HTML file ---
coef_plot_path = OUT_QUESTION1 / "ols_coefficient_plot.html"
fig_coef.write_html(coef_plot_path)

print(f"\nCoefficient plot saved to: {coef_plot_path}")

# Show the plot in the notebook
fig_coef.show()

Coefficient plot saved to: c:\Users\dirai\Documents\GitHub\kldr-project\app\data\output\question1\ols_coefficient_plot.html