## Question 3 "How are digital service exports growing by region?"

for this, I want to use the DiD approach, first we have to define regions

In [1]:
# import all relevant libraries --> can't use utils since it is a jupyter notebook
import streamlit as st
import pandas as pd
from pathlib import Path
import plotly.express as px
import numpy as np

In [2]:
CWD = Path.cwd()
print(CWD)

ROOT = CWD.parent

IN_RAW = ROOT/"app"/"data"/"output"

OUT_CLEAN = ROOT/"app"/"data"/"output"

OUT_TABLES = ROOT/"app"/"data"/"tables"

IN_DATASET = ROOT/"app"/"data"/"output"/"question1" #<---- here is what we need

print(ROOT)
print(IN_RAW)
print(IN_DATASET)

c:\Users\dirai\Documents\GitHub\kldr-project\scripts
c:\Users\dirai\Documents\GitHub\kldr-project
c:\Users\dirai\Documents\GitHub\kldr-project\app\data\output
c:\Users\dirai\Documents\GitHub\kldr-project\app\data\output\question1

In [3]:
df_raw = pd.read_csv(IN_DATASET/"final_panel_for_regression.csv")

In [58]:
df = df_raw.copy()

In [59]:
# load the messing regions column
# fetch region and adminregion
import wbdata
from datetime import datetime
indicators ={
    "region":"Region Name",
    "adminregion": "Administrative Region Name"
}

df_regions_raw = wbdata.get_countries(country_id="all")

In [60]:
df_regions_raw = pd.DataFrame(df_regions_raw)

df_regions_raw.head()

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
2,AFG,AF,Afghanistan,"{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228
3,AFR,A9,Africa,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
4,AFW,ZI,Africa Western and Central,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,

In [61]:
def get_value_dict(cell):
    if isinstance(cell, dict):
        return cell.get("value")
    return None
df_regions_raw["region_name"] = df_regions_raw["region"].apply(get_value_dict)
df_regions_raw['admin_region_name'] = df_regions_raw['adminregion'].apply(get_value_dict)

df_regions_raw

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude,region_name,admin_region_name
0,ABW,AW,Aruba,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167,Latin America & Caribbean,
1,AFE,ZH,Africa Eastern and Southern,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,,Aggregates,
2,AFG,AF,Afghanistan,"{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228,"Middle East, North Africa, Afghanistan & Pakistan","Middle East, North Africa, Afghanistan & Pakis..."
3,AFR,A9,Africa,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,,Aggregates,
4,AFW,ZI,Africa Western and Central,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,,Aggregates,
...,...,...,...,...,...,...,...,...,...,...,...,...
291,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,,Aggregates,
292,YEM,YE,"Yemen, Rep.","{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Sana'a,44.2075,15.352,"Middle East, North Africa, Afghanistan & Pakistan","Middle East, North Africa, Afghanistan & Pakis..."
293,ZAF,ZA,South Africa,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Pretoria,28.1871,-25.746,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income)
294,ZMB,ZM,Zambia,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Lusaka,28.2937,-15.3982,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income)
295,ZWE,ZW,Zimbabwe,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'}",Harare,31.0672,-17.8312,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income)

In [62]:
df_regions_raw["region_name"] = df_regions_raw["region"].apply(get_value_dict)
df_regions_raw['admin_region_name'] = df_regions_raw['adminregion'].apply(get_value_dict)

In [64]:
df_regions_raw["region_final"] = df_regions_raw["region_name"].fillna(df_regions_raw["admin_region_name"])

In [65]:
# filter aggregates

df_countries_only = df_regions_raw[df_regions_raw["region_final"] != "Aggregates"].copy()
df_countries_only.head()

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude,region_name,admin_region_name,region_final
0,ABW,AW,Aruba,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167,Latin America & Caribbean,,Latin America & Caribbean
2,AFG,AF,Afghanistan,"{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228,"Middle East, North Africa, Afghanistan & Pakistan","Middle East, North Africa, Afghanistan & Pakis...","Middle East, North Africa, Afghanistan & Pakistan"
5,AGO,AO,Angola,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Luanda,13.242,-8.81155,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Sub-Saharan Africa
6,ALB,AL,Albania,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro...","{'id': 'ECA', 'iso2code': '7E', 'value': 'Euro...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Tirane,19.8172,41.3317,Europe & Central Asia,Europe & Central Asia (excluding high income),Europe & Central Asia
7,AND,AD,Andorra,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Andorra la Vella,1.5218,42.5075,Europe & Central Asia,,Europe & Central Asia

In [66]:
# selecet and rename final columns for merge

df_regions_final = df_countries_only[["id", "region_final"]].rename(
    columns = {"id": "country_code",
                "region_final": "region"}
)

df_regions_final

    country_code                                             region
0            ABW                         Latin America & Caribbean
2            AFG  Middle East, North Africa, Afghanistan & Pakistan
5            AGO                                Sub-Saharan Africa
6            ALB                              Europe & Central Asia
7            AND                              Europe & Central Asia
..           ...                                                ...
290          XKX                              Europe & Central Asia
292          YEM  Middle East, North Africa, Afghanistan & Pakistan
293          ZAF                                Sub-Saharan Africa
294          ZMB                                Sub-Saharan Africa
295          ZWE                                Sub-Saharan Africa

[217 rows x 2 columns]

In [67]:
df_regions_final.dropna(subset=["region"], inplace = True)

df_regions_final

    country_code                                             region
0            ABW                         Latin America & Caribbean
2            AFG  Middle East, North Africa, Afghanistan & Pakistan
5            AGO                                Sub-Saharan Africa
6            ALB                              Europe & Central Asia
7            AND                              Europe & Central Asia
..           ...                                                ...
290          XKX                              Europe & Central Asia
292          YEM  Middle East, North Africa, Afghanistan & Pakistan
293          ZAF                                Sub-Saharan Africa
294          ZMB                                Sub-Saharan Africa
295          ZWE                                Sub-Saharan Africa

[217 rows x 2 columns]

In [68]:
df_main = df # panel dataset

df_merged = pd.merge(
    left=df_main,
    right=df_regions_final,
    how = "left",
    on= "country_code"
)
(df_merged["region"].nunique(), df_merged["region"].unique())

(7,
 array(['Latin America & Caribbean ',
        'Middle East, North Africa, Afghanistan & Pakistan',
        'Sub-Saharan Africa ', 'Europe & Central Asia',
        'East Asia & Pacific', 'South Asia', 'North America'], dtype=object))

In [73]:
df_merged.to_csv(OUT_CLEAN/"question3"/"df_merged_for_DiD.csv")

### Now about the DiD analysis:

In [74]:
import statsmodels.formula.api as smf

df_model = df_merged.copy()

df_model.dropna(subset=['Exports_Digital_Service', 'year', 'region'], inplace=True)


# a) Create the dependent variable: log_exports
df_model["log_exports"] = np.log(df_model["Exports_Digital_Service"]+1)

# b) Create a normalized time variable (starts from 0)
df_model["time"] = df_model["year"] -df_model["year"].min()


# --- 2. Define and Run the Regression Model ---

# The formula specifies the model:
# log_exports is the dependent variable.
# 'time * C(region)' tells statsmodels to include:
#   - The main effect of time ('time')
#   - The main effect of region (dummy variables for each region)
#   - The interaction effect between time and each region dummy


formula = "log_exports ~time * C(region)"

model = smf.ols(formula=formula, data = df_model)

results = model.fit()

In [75]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            log_exports   R-squared:                       0.204
Model:                            OLS   Adj. R-squared:                  0.200
Method:                 Least Squares   F-statistic:                     46.37
Date:                Mon, 01 Dec 2025   Prob (F-statistic):          1.31e-106
Time:                        13:57:00   Log-Likelihood:                -6305.7
No. Observations:                2367   AIC:                         1.264e+04
Df Residuals:                    2353   BIC:                         1.272e+04
Df Model:                          13
Covariance Type:            nonrobust
=======================================================================================================================================
                                                                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------------------------
Intercept                                                              32.2046      0.338     95.333      0.000      31.542      32.867
C(region)[T.Europe & Central Asia]                                      3.3056      0.425      7.770      0.000       2.471       4.140
C(region)[T.Latin America & Caribbean ]                                 0.7667      0.466      1.645      0.100      -0.147       1.681
C(region)[T.Middle East, North Africa, Afghanistan & Pakistan]          2.0884      0.523      3.991      0.000       1.062       3.115
C(region)[T.North America]                                              4.9686      1.094      4.540      0.000       2.822       7.115
C(region)[T.South Asia]                                                 1.3920      0.845      1.648      0.100      -0.264       3.048
C(region)[T.Sub-Saharan Africa ]                                       -0.3736      0.434     -0.860      0.390      -1.226       0.478
time                                                                    0.0795      0.046      1.716      0.086      -0.011       0.170
time:C(region)[T.Europe & Central Asia]                                 0.0148      0.057      0.258      0.797      -0.098       0.127
time:C(region)[T.Latin America & Caribbean ]                           -0.0385      0.063     -0.607      0.544      -0.163       0.086
time:C(region)[T.Middle East, North Africa, Afghanistan & Pakistan]     0.0027      0.072      0.038      0.970      -0.138       0.144
time:C(region)[T.North America]                                         0.1416      0.155      0.912      0.362      -0.163       0.446
time:C(region)[T.South Asia]                                           -0.0542      0.111     -0.489      0.625      -0.272       0.163
time:C(region)[T.Sub-Saharan Africa ]                                  -0.0648      0.060     -1.072      0.284      -0.183       0.054
==============================================================================
Omnibus:                     2383.598   Durbin-Watson:                   0.325
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           198271.751
Skew:                          -4.726   Prob(JB):                         0.00
Kurtosis:                      46.830   Cond. No.                         133.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [77]:
# --- 4. Explanation of How to Interpret the Results ---

print("\n\n--- How to Interpret These Results ---")
print("This model tells us if the growth trend of digital exports differs across regions.")
print("\n1. **Baseline Region:** Statsmodels automatically chose one region as the baseline for comparison. This is the region that is *not* listed in the variable names below.")

print("\n2. **Interaction Terms (time:C(region)[...]):** These are the most important coefficients.")
print("   - A **positive** coefficient for 'time:C(region)[T.Asia]' means that, on average, digital exports in Asia grew faster each year compared to the baseline region.")
print("   - A **negative** coefficient means the growth was slower than the baseline.")
print("   - Check the 'P>|t|' column. A value less than 0.05 indicates the difference in trend is statistically significant.")

print("\n3. **Main Effects (C(region)[...]):** These coefficients show the difference in the *starting level* of digital exports in 2010 compared to the baseline region.")

--- How to Interpret These Results ---
This model tells us if the growth trend of digital exports differs across regions.

1. **Baseline Region:** Statsmodels automatically chose one region as the baseline for comparison. This is the region that is *not* listed in the variable names below.

2. **Interaction Terms (time:C(region)[...]):** These are the most important coefficients.
   - A **positive** coefficient for 'time:C(region)[T.Asia]' means that, on average, digital exports in Asia grew faster each year compared to the baseline region.
   - A **negative** coefficient means the growth was slower than the baseline.
   - Check the 'P>|t|' column. A value less than 0.05 indicates the difference in trend is statistically significant.

3. **Main Effects (C(region)[...]):** These coefficients show the difference in the *starting level* of digital exports in 2010 compared to the baseline region.

In [78]:
# create a .txt file

summary_output_path = ROOT/"app"/"data"/"output"/"question3"/"regional_export_growth.txt"

with open(summary_output_path, "w") as f:
    f.write(str(results.summary()))

print(summary_output_path)

c:\Users\dirai\Documents\GitHub\kldr-project\app\data\output\question3\regional_export_growth.txt

In [79]:
with open(summary_output_path) as f:
    print(f.read())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log_exports   R-squared:                       0.204
Model:                            OLS   Adj. R-squared:                  0.200
Method:                 Least Squares   F-statistic:                     46.37
Date:                Mon, 01 Dec 2025   Prob (F-statistic):          1.31e-106
Time:                        14:51:27   Log-Likelihood:                -6305.7
No. Observations:                2367   AIC:                         1.264e+04
Df Residuals:                    2353   BIC:                         1.272e+04
Df Model:                          13
Covariance Type:            nonrobust
=======================================================================================================================================
                                                                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------------------------
Intercept                                                              32.2046      0.338     95.333      0.000      31.542      32.867
C(region)[T.Europe & Central Asia]                                      3.3056      0.425      7.770      0.000       2.471       4.140
C(region)[T.Latin America & Caribbean ]                                 0.7667      0.466      1.645      0.100      -0.147       1.681
C(region)[T.Middle East, North Africa, Afghanistan & Pakistan]          2.0884      0.523      3.991      0.000       1.062       3.115
C(region)[T.North America]                                              4.9686      1.094      4.540      0.000       2.822       7.115
C(region)[T.South Asia]                                                 1.3920      0.845      1.648      0.100      -0.264       3.048
C(region)[T.Sub-Saharan Africa ]                                       -0.3736      0.434     -0.860      0.390      -1.226       0.478
time                                                                    0.0795      0.046      1.716      0.086      -0.011       0.170
time:C(region)[T.Europe & Central Asia]                                 0.0148      0.057      0.258      0.797      -0.098       0.127
time:C(region)[T.Latin America & Caribbean ]                           -0.0385      0.063     -0.607      0.544      -0.163       0.086
time:C(region)[T.Middle East, North Africa, Afghanistan & Pakistan]     0.0027      0.072      0.038      0.970      -0.138       0.144
time:C(region)[T.North America]                                         0.1416      0.155      0.912      0.362      -0.163       0.446
time:C(region)[T.South Asia]                                           -0.0542      0.111     -0.489      0.625      -0.272       0.163
time:C(region)[T.Sub-Saharan Africa ]                                  -0.0648      0.060     -1.072      0.284      -0.183       0.054
==============================================================================
Omnibus:                     2383.598   Durbin-Watson:                   0.325
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           198271.751
Skew:                          -4.726   Prob(JB):                         0.00
Kurtosis:                      46.830   Cond. No.                         133.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.